---
- hosts: storage
  become: yes
  vars_files:
    - group_vars/storage.yml
  tasks:
    - name: Dependencies
      import_tasks: tasks/rclone.yml
    - name: Install service
      import_tasks: tasks/install.yml
